# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9d4c014a723d344cf8629e8b9115082603e3c7d521ee67fd4efaefacb354e7744f12ce8d8300722faa04f940c740a294d1c95cdc2d1a8fa7ec5824b46e786b52

test:
  secret_key_base: cf096acd92064e016e0924395be5fb6533feb30aedce496320bcfd1ca77bed68b640e1d31ea68e8b6b2dcc70c4f859cd6a7fd01a2c24927db527205804360985

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
